vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        customers:
            uri_prefix: app.path.customer_images
            upload_destination: '%kernel.project_dir%/public/images/customers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        
        profile:
            uri_prefix: app.path.profile_images
            upload_destination: '%kernel.project_dir%/public/images/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
