vich_uploader:
    db_driver: orm

    mappings:
        profile:
            uri_prefix: /images/profile
            upload_destination: '%kernel.project_dir%/public/images/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        clients:
            uri_prefix: /images/customer
            upload_destination: '%kernel.project_dir%/public/images/customer'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer