vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        clients:
            uri_prefix: /images/customers
            upload_destination: '%kernel.project_dir%/public/images/customers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        profile:
            uri_prefix: /images/profile
            upload_destination: '%kernel.project_dir%/public/images/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
