version: '3'

services:
  
###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    environment:
      MYSQL_DATABASE: gestion-beaute
      MYSQL_ROOT_PASSWORD: root

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
