version: '3'

services:
  
###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    restart: always
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: gestion-beaute
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    container_name: docker_phpmyadmin
    restart: always
    depends_on: 
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database

  

  


